apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: cert-manager
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: devops.goupaz.com
  dnsNames:
  - devops.goupaz.com
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - devops.goupaz.com