apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-ingress
spec:
  secretName: ingress-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: devops.goupaz.com
  dnsNames:
  - devops.goupaz.com
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - devops.goupaz.com